addons:
  apt:
    packages:
      - python-pygments
install:
  - rm -rf public || exit 0
  - wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  name: n33m4
  email: n33m4@yahoo.com
  on:
    branch: master
